### ISSUE TITLE
Unable to clone GitHub repo via ssh

### ISSUE THREAD

**Issue by clach04** [catpuppyapp/PuppyGit#5]
I noticed in https://github.com/catpuppyapp/PuppyGit/releases/tag/1.0.6.4v40 SSH support was added (as mentioned in https://github.com/gsantner/markor/discussions/2457)

So I tried out https://github.com/catpuppyapp/PuppyGit/releases/tag/1.0.6.5v41 from today.

I can't see how to clone a github ssh URL, for example, `git@github.com:clach04/puren_tonbo.git`. The dialog box seems to only show username and password. I can not see anywhere to manage ssh keys. I'm not sure I've ever seen a public git server ssh without key support.

User error or is this a feature-request?

**Comment by Bandeapart1964** [comment]
1 the username and password text filed now updated.
2 puppygit doesn't support generate ssh keys.

**Comment by Bandeapart1964** [comment]
for me, support ssh is support connect by ssh, is not means generate and manage your ssh keys on the app. but if users needed, I'll consider implement it.

**Comment by Bandeapart1964** [comment]
i will close this issue, if have any other question, re open it

**Comment by Bandeapart1964** [comment]
hi, indeed is a bug, when edit a cloned err repo, the new credential on clone screen will show username/password ever until you  change the git url,  tomorrow will fixed

**Comment by Bandeapart1964** [comment]
fixed, check new release, if have any quest, reopen the issue of create new one
https://github.com/catpuppyapp/PuppyGit/releases/tag/1.0.6.7v43

**Comment by clach04** [comment]
@Bandeapart1964 cool! Installed and new UI looks good, I can confirm it is not longer asking for username :-) I was in a rush so will have to test key tomorrow.

I agree with you, key generation is out of scope for a git client app 👍

**Comment by clach04** [comment]
Clone, simple quick text file edit, commit+push all seems to work!

I'm still getting my head around the UI/UX. It's very neat having a text editor built-in 👍 
I've been using mgit (which doesn't have a text editor built in).

**Comment by Bandeapart1964** [comment]
> Clone, simple quick text file edit, commit+push all seems to work!
> 
> I'm still getting my head around the UI/UX. It's very neat having a text editor built-in 👍 
> I've been using mgit (which doesn't have a text editor built in).

glad to hear everything works as expected, and I was using mgit too 😄
